# Generated by Django 4.2.5 on 2023-09-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
